name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Run basic test
        run: echo "No tests yet"

      - name: Run TruffleHog Secret Scan
        uses: edplato/trufflehog-actions-scan@v1.0.4
        with:
          scanArguments: --regex --entropy=True
